version: "3"

services:
  ai_cartasur:
    platform: linux/amd64
    build:
      context: ./ai_cartasur_api/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./ai_cartasur_api:/app
      - ./data/:/data
    depends_on:
      - ai_cartasur_db
    networks:
      - cartasur

  ai_cartasur_db:
    image: postgres:14.3-bullseye
    env_file:
      - .env
    volumes:
      - ./ai_cartasur_db:/var/lib/postgresql/data
    networks:
      - cartasur

networks:
  cartasur:
